name: Release
on:
  push: { tags: [ 'v*' ] }
permissions:
  deployments: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Package the source
        run: |
          tar -cvf report.tar.gz *

      - name: Crease a release
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "report.tar.gz"
